const fs = require('fs');
const path = require('path');

const TOKENS_DIR = path.join(__dirname, '../tokens');
const OUT_DIR = path.join(__dirname, '..');

// Merge all token files
function mergeTokenFiles() {
  const merged = {};
  const files = fs.readdirSync(TOKENS_DIR).filter(f => f.endsWith('.json'));
  for (const file of files) {
    const data = JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, file), 'utf-8'));
    deepMerge(merged, data);
  }
  return merged;
}

function deepMerge(target, source) {
  for (const key of Object.keys(source)) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      if (!target[key]) target[key] = {};
      deepMerge(target[key], source[key]);
    } else {
      target[key] = source[key];
    }
  }
  return target;
}

// Flatten tokens to dot-notation paths
function flattenTokens(obj, prefix = '') {
  const result = {};
  for (const [key, val] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (val && typeof val === 'object' && 'value' in val && 'type' in val) {
      result[path] = val;
    } else if (val && typeof val === 'object') {
      Object.assign(result, flattenTokens(val, path));
    }
  }
  return result;
}

// Convert dot-path to CSS var name: color.semantic.text.strong → --color-semantic-text-strong
function toCssVar(path) {
  return '--' + path.replace(/\./g, '-');
}

// Generate color CSS custom properties for a given mode
function generateColorCss(flat, mode) {
  const lines = [`:root[data-theme="${mode}"], .theme-${mode} {`];
  for (const [tokenPath, token] of Object.entries(flat)) {
    if (token.type !== 'color') continue;
    const val = typeof token.value === 'object' && 'light' in token.value
      ? token.value[mode] ?? token.value.light
      : token.value;
    if (val) lines.push(`  ${toCssVar(tokenPath)}: ${val};`);
  }
  lines.push('}');
  return lines.join('\n');
}

// Generate typography CSS custom properties
function generateTypographyCss(flat) {
  const lines = [':root {'];
  for (const [tokenPath, token] of Object.entries(flat)) {
    if (token.type === 'fontFamily') {
      lines.push(`  ${toCssVar(tokenPath)}: '${token.value}', -apple-system, sans-serif;`);
    } else if (token.type === 'fontWeight') {
      lines.push(`  ${toCssVar(tokenPath)}: ${token.value};`);
    } else if (token.type === 'typography') {
      const v = token.value;
      lines.push(`  ${toCssVar(tokenPath)}-size: ${v.size}px;`);
      lines.push(`  ${toCssVar(tokenPath)}-weight: ${v.weight};`);
      lines.push(`  ${toCssVar(tokenPath)}-line-height: ${v.lineHeight};`);
    }
  }
  lines.push('}');
  return lines.join('\n');
}

function main() {
  const merged = mergeTokenFiles();
  const flat = flattenTokens(merged);

  // Save tokens.json
  fs.writeFileSync(
    path.join(OUT_DIR, 'tokens.json'),
    JSON.stringify(flat, null, 2),
    'utf-8'
  );

  // @font-face
  const fontFace = `@font-face {
  font-family: 'Pretendard';
  src: url('./fonts/PretendardVariable.ttf') format('truetype');
  font-weight: 100 900;
  font-style: normal;
  font-display: swap;
}`;

  // Color CSS
  const lightCss = generateColorCss(flat, 'light');
  const darkCss  = generateColorCss(flat, 'dark');
  const mediaQuery = `@media (prefers-color-scheme: dark) {\n  :root {\n${
    Object.entries(flat)
      .filter(([, t]) => t.type === 'color' && typeof t.value === 'object' && 'dark' in t.value)
      .map(([p, t]) => `    ${toCssVar(p)}: ${t.value.dark};`)
      .join('\n')
  }\n  }\n}`;

  // Typography CSS
  const typographyCss = generateTypographyCss(flat);

  const css = [
    '/* TDS Design Tokens — Auto-generated by build-tokens.js */',
    '/* DO NOT EDIT DIRECTLY — edit tokens/*.json and rebuild */',
    '',
    fontFace,
    '',
    lightCss,
    '',
    darkCss,
    '',
    mediaQuery,
    '',
    typographyCss,
  ].join('\n');

  fs.writeFileSync(path.join(OUT_DIR, 'variables.css'), css, 'utf-8');

  const colorCount = Object.values(flat).filter(t => t.type === 'color').length;
  const typoCount  = Object.values(flat).filter(t => t.type === 'typography').length;
  console.log(`✓ tokens.json  — ${Object.keys(flat).length} total tokens`);
  console.log(`✓ variables.css — ${colorCount} color + ${typoCount} typography tokens`);
}

main();
